### PR TITLE
Created a home page and Blog Posts Page

### PR DESCRIPTION
**Pull request by iamsusmitha**
I have created a Home Page and Blog Posts page and yet to complete Hall Of Fame page.

### CODE REVIEW

**Comment by iamsusmitha** [comment]
I am herewith attaching the screen shots of home page created
screenshot 318
screenshot 319
screenshot 320

**Comment by iamsusmitha** [comment]
I have also created Blog Posts Page and herewith attaching the screenshots.

screenshot 321


screenshot 322


screenshot 323


screenshot 324

**Comment by iamsusmitha** [comment]
In footer section the "Github" link will direct to the FossClub organization of github

**Comment by iamsusmitha** [comment]
Please let me know any changes or suggestions regarding those two pages...... @daminisatya @kavithaenair

**Comment by Sush97** [comment]
Files Added

**Pull request closed without merging**
