### PR TITLE
Deleted all files

### PR DESCRIPTION
**Pull request by Pranavya**
As you wanted us to do the website from scratch.I deleted all the files

### CODE REVIEW

**Review by kavithaenair — CHANGES_REQUESTED** [review]
@Pranavya Instead of deleting all the files, I think you can just edit the code in the files. What do you think @daminisatya ?

And Please do create an issue first and put that issue id in the PR description.

**Comment by Pranavya** [comment]
if not deleting files, what i have to do instead? @kavithaenair  @daminisatya

**Comment by iamsusmitha** [comment]
@kavithaenair You mean editing the whole code in the files with same filenames or just editing bits of code for a slight change in UI(designing) in the existing one??

**Comment by Pranavya** [comment]
I think she suggested to edit the code in existing files @Sush97

**Comment by daminisatya** [comment]
Ok, for now, let's take this and clear the junk.

**Comment by iamsusmitha** [comment]
Okay @daminisatya

**Pull request merged**
